### ISSUE TITLE
Request for adding `bind_front` and `bind_back`

### ISSUE THREAD

**Issue by ashtum** [boostorg/compat#6]
`bind_front` and `bind_back` are very handy wrappers, especially for asynchronous applications where we want to pass member functions as completion handlers. Unfortunately, their standard counterparts require C++20 and C++23, respectively.

Considering their implementation, we might get `invoke` and probably `apply` as byproducts.

**Comment by pdimov** [comment]
I intend to work on these after 1.85 ships.

**Comment by pdimov** [comment]
`bind_front`, `bind_back`, `invoke` implemented on develop.
